In [19]:
import numpy as np

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.datasets import load_digits
digits=load_digits()

In [20]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(digits.data, digits.target, test_size=0.2)

In [21]:
lr=LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

C:\Users\priya\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9805555555555555

In [22]:
svm=SVC()
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.9888888888888889

In [23]:
rfc=RandomForestClassifier()
rfc.fit(x_train,y_train)
rfc.score(x_test,y_test)

0.9833333333333333

In [9]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=6)
kf

KFold(n_splits=6, random_state=None, shuffle=False)

In [10]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,4,6,9,8,0,6,7,8]):
    print(train_index,test_index)

[ 3  4  5  6  7  8  9 10 11 12 13 14 15] [0 1 2]
[ 0  1  2  6  7  8  9 10 11 12 13 14 15] [3 4 5]
[ 0  1  2  3  4  5  9 10 11 12 13 14 15] [6 7 8]
[ 0  1  2  3  4  5  6  7  8 12 13 14 15] [ 9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11 14 15] [12 13]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13] [14 15]


In [26]:
def get_score(model, x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [27]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)

In [28]:

scores_logistics=[]
scores_svm=[]
scores_rf=[]

for train_index, test_index in folds.split(digits.data, digits.target):
    x_train, x_test, y_train, y_test=digits.data[train_index],digits.data[test_index],\
                    digits.target[train_index], digits.target[test_index]
    scores_logistics.append(get_score(LogisticRegression(), x_train,x_test,y_train,y_test))
    scores_svm.append(get_score(SVC(),x_train,x_test,y_train,y_test))
    scores_rf.append(get_score(RandomForestClassifier(),x_train,x_test,y_train,y_test))

C:\Users\priya\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\priya\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

In [29]:
scores_logistics

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]

In [30]:
scores_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [31]:
scores_rf

[0.9432387312186978, 0.9532554257095158, 0.9248747913188647]

In [32]:
from sklearn.model_selection import cross_val_score

In [33]:
cross_val_score(LogisticRegression(),digits.data, digits.target, cv=3)

C:\Users\priya\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\priya\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

array([0.92153589, 0.94156928, 0.91652755])

In [34]:
cross_val_score(SVC(),digits.data, digits.target, cv=3)

array([0.96494157, 0.97996661, 0.96494157])

In [35]:
cross_val_score(RandomForestClassifier(),digits.data, digits.target, cv=3)

array([0.93489149, 0.94824708, 0.92320534])

In [36]:
score1=cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=3)
np.average(score1)

0.8486366165831942

In [37]:
score2=cross_val_score(RandomForestClassifier(n_estimators=10),digits.data, digits.target, cv=3)
np.average(score2)

0.8914858096828047

In [38]:
score3=cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target, cv=3)
np.average(score3)

0.9209794101279911

In [39]:
score4=cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=3)
np.average(score4)

0.9298831385642737